version: "2017-09-20"
dependencies:
    - id: base
      type: docker
      ref: registry.opensource.zalan.do/stups/ubuntu
pipeline:
  - id: build
    type: script
    commands:
    - desc: 'Install Docker'
      cmd: 'curl -sSL https://delivery.cloud.zalando.com/utils/ensure-docker | sh'
    - desc: 'Build JDK 8 image'
      cmd: ./build.sh 8
    - desc: 'Build JDK 11 image'
      cmd: ./build.sh 11
